
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: teju2304
    url: jdbc:mysql://localhost:3306/studentRestApi
    username: root
  application:
    name: student-api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  springdoc:
    swagger-ui:
      path: swagger-ui.html